springfox:
  documentation:
    swagger-ui:
      enabled: true

server:
  port: 8088
  servlet:
    context-path: /covid-web-api

covid:
  api:
    url:
      summary: https://api.covid19api.com/summary
      status-api: https://covid19-brazil-api.now.sh/api/status/v1
      data-especifica-brasil: https://covid19-brazil-api.now.sh/api/report/v1/brazil/

